/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jonesx_audioplayer_AudioPlayer */

#ifndef _Included_com_dy_ffmpeg_PlayMusicActivity
#define _Included_com_dy_ffmpeg_PlayMusicActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jonesx_audioplayer_AudioPlayer
 * Method:    play
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dy_ffmpeg_PlayMusicActivity_play
        (JNIEnv *, jclass);

/*
 * Class:     jonesx_audioplayer_AudioPlayer
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dy_ffmpeg_PlayMusicActivity_stop
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
